name: fb2
description: FB2 Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
version: 0.0.1
homepage: https://github.com/dkrutskikh/dart-fb2

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  dart_code_metrics: ^2.0.0
  dependency_validator: ^1.5.0
  mockito: ^4.1.1
  pedantic: ^1.9.2
  test: ^1.15.3
