name: fb2
description: FB2 Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
version: 0.0.1
homepage: https://github.com/dkrutskikh/dart-fb2

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  coverage: ^1.3.1
  dart_code_metrics: ">=4.15.0 <6.0.0"
  lints: ^2.0.0
  mocktail: ^0.3.0
  path: ^1.8.1
  test: ^1.21.0
