import 'package:xml/xml.dart';

import '../entities/fb2_creator.dart';
import '../entities/fb2_genre.dart';
import '../entities/fb2_title.dart';

Fb2Title readTitle(XmlNode fictionBookDecriptionTitle) => Fb2Title(
      title: fictionBookDecriptionTitle.getElement('book-title')?.text,
      authors: fictionBookDecriptionTitle.children
          .whereType<XmlElement>()
          .where((e) => e.name.toString() == 'author')
          .map(_readCreator)
          .toList(),
      genres: fictionBookDecriptionTitle.children
          .whereType<XmlElement>()
          .where((e) => e.name.toString() == 'genre')
          .map((e) => _genres[e?.text])
          .toList(),
    );

Fb2Creator _readCreator(XmlNode authorNode) {
  final uri = authorNode?.getElement('home-page')?.text;

  return Fb2Creator(
    firstName: authorNode?.getElement('first-name')?.text,
    middleName: authorNode?.getElement('middle-name')?.text,
    lastName: authorNode?.getElement('last-name')?.text,
    nickname: authorNode?.getElement('nickname')?.text,
    homePage: uri != null ? Uri.parse(uri) : null,
    email: authorNode?.getElement('email')?.text,
    id: authorNode?.getElement('id')?.text,
  );
}

const _genres = {
  'accounting': Fb2Genre.accounting,
  'adv_animal': Fb2Genre.advAnimal,
  'adv_geo': Fb2Genre.advGeo,
  'adv_history': Fb2Genre.advHistory,
  'adv_maritime': Fb2Genre.advMaritime,
  'adv_western': Fb2Genre.advWestern,
  'adventure': Fb2Genre.adventure,
  'antique': Fb2Genre.antique,
  'antique_ant': Fb2Genre.antiqueAnt,
  'antique_east': Fb2Genre.antiqueEast,
  'antique_european': Fb2Genre.antiqueEuropean,
  'antique_myths': Fb2Genre.antiqueMyths,
  'antique_russian': Fb2Genre.antiqueRussian,
  'aphorism_quote': Fb2Genre.aphorismQuote,
  'architecture_book': Fb2Genre.architectureBook,
  'auto_regulations': Fb2Genre.autoRegulations,
  'banking': Fb2Genre.banking,
  'beginning_authors': Fb2Genre.beginningAuthors,
  'child_adv': Fb2Genre.childAdv,
  'child_det': Fb2Genre.childDet,
  'child_education': Fb2Genre.childEducation,
  'child_prose': Fb2Genre.childProse,
  'child_sf': Fb2Genre.childSf,
  'child_tale': Fb2Genre.childTale,
  'child_verse': Fb2Genre.childVerse,
  'children': Fb2Genre.children,
  'cinema_theatre': Fb2Genre.cinemaTheatre,
  'city_fantasy': Fb2Genre.cityFantasy,
  'comp_db': Fb2Genre.compDb,
  'comp_hard': Fb2Genre.compHard,
  'comp_osnet': Fb2Genre.compOsnet,
  'comp_programming': Fb2Genre.compProgramming,
  'comp_soft': Fb2Genre.compSoft,
  'comp_www': Fb2Genre.compWww,
  'computers': Fb2Genre.computers,
  'design': Fb2Genre.design,
  'det_action': Fb2Genre.detAction,
  'det_classic': Fb2Genre.detClassic,
  'det_crime': Fb2Genre.detCrime,
  'det_espionage': Fb2Genre.detEspionage,
  'det_hard': Fb2Genre.detHard,
  'det_history': Fb2Genre.detHistory,
  'det_irony': Fb2Genre.detIrony,
  'det_police': Fb2Genre.detPolice,
  'det_political': Fb2Genre.detPolitical,
  'detective': Fb2Genre.detective,
  'dragon_fantasy': Fb2Genre.dragonFantasy,
  'dramaturgy': Fb2Genre.dramaturgy,
  'economics': Fb2Genre.economics,
  'essays': Fb2Genre.essays,
  'fantasy_fight': Fb2Genre.fantasyFight,
  'foreign_action': Fb2Genre.foreignAction,
  'foreign_adventure': Fb2Genre.foreignAdventure,
  'foreign_antique': Fb2Genre.foreignAntique,
  'foreign_business': Fb2Genre.foreignBusiness,
  'foreign_children': Fb2Genre.foreignChildren,
  'foreign_comp': Fb2Genre.foreignComp,
  'foreign_contemporary': Fb2Genre.foreignContemporary,
  'foreign_contemporary_lit': Fb2Genre.foreignContemporaryLit,
  'foreign_desc': Fb2Genre.foreignDesc,
  'foreign_detective': Fb2Genre.foreignDetective,
  'foreign_dramaturgy': Fb2Genre.foreignDramaturgy,
  'foreign_edu': Fb2Genre.foreignEdu,
  'foreign_fantasy': Fb2Genre.foreignFantasy,
  'foreign_home': Fb2Genre.foreignHome,
  'foreign_humor': Fb2Genre.foreignHumor,
  'foreign_language': Fb2Genre.foreignLanguage,
  'foreign_love': Fb2Genre.foreignLove,
  'foreign_novel': Fb2Genre.foreignNovel,
  'foreign_other': Fb2Genre.foreignOther,
  'foreign_poetry': Fb2Genre.foreignPoetry,
  'foreign_prose': Fb2Genre.foreignProse,
  'foreign_psychology': Fb2Genre.foreignPsychology,
  'foreign_publicism': Fb2Genre.foreignPublicism,
  'foreign_religion': Fb2Genre.foreignReligion,
  'foreign_sf': Fb2Genre.foreignSf,
  'geo_guides': Fb2Genre.geoGuides,
  'geography_book': Fb2Genre.geographyBook,
  'global_economy': Fb2Genre.globalEconomy,
  'historical_fantasy': Fb2Genre.historicalFantasy,
  'home': Fb2Genre.home,
  'home_cooking': Fb2Genre.homeCooking,
  'home_crafts': Fb2Genre.homeCrafts,
  'home_diy': Fb2Genre.homeDiy,
  'home_entertain': Fb2Genre.homeEntertain,
  'home_garden': Fb2Genre.homeGarden,
  'home_health': Fb2Genre.homeHealth,
  'home_pets': Fb2Genre.homePets,
  'home_sex': Fb2Genre.homeSex,
  'home_sport': Fb2Genre.homeSport,
  'humor': Fb2Genre.humor,
  'humor_anecdote': Fb2Genre.humorAnecdote,
  'humor_fantasy': Fb2Genre.humorFantasy,
  'humor_prose': Fb2Genre.humorProse,
  'humor_verse': Fb2Genre.humorVerse,
  'industries': Fb2Genre.industries,
  'job_hunting': Fb2Genre.jobHunting,
  'literature_18': Fb2Genre.literature18,
  'literature_19': Fb2Genre.literature19,
  'literature_20': Fb2Genre.literature20,
  'love_contemporary': Fb2Genre.loveContemporary,
  'love_detective': Fb2Genre.loveDetective,
  'love_erotica': Fb2Genre.loveErotica,
  'love_fantasy': Fb2Genre.loveFantasy,
  'love_history': Fb2Genre.loveHistory,
  'love_sf': Fb2Genre.loveSf,
  'love_short': Fb2Genre.loveShort,
  'magician_book': Fb2Genre.magicianBook,
  'management': Fb2Genre.management,
  'marketing': Fb2Genre.marketing,
  'military_special': Fb2Genre.militarySpecial,
  'music_dancing': Fb2Genre.musicDancing,
  'narrative': Fb2Genre.narrative,
  'newspapers': Fb2Genre.newspapers,
  'nonf_biography': Fb2Genre.nonfBiography,
  'nonf_criticism': Fb2Genre.nonfCriticism,
  'nonf_publicism': Fb2Genre.nonfPublicism,
  'nonfiction': Fb2Genre.nonfiction,
  'org_behavior': Fb2Genre.orgBehavior,
  'paper_work': Fb2Genre.paperWork,
  'pedagogy_book': Fb2Genre.pedagogyBook,
  'periodic': Fb2Genre.periodic,
  'personal_finance': Fb2Genre.personalFinance,
  'poetry': Fb2Genre.poetry,
  'popadanec': Fb2Genre.popadanec,
  'popular_business': Fb2Genre.popularBusiness,
  'prose_classic': Fb2Genre.proseClassic,
  'prose_counter': Fb2Genre.proseCounter,
  'prose_history': Fb2Genre.proseHistory,
  'prose_military': Fb2Genre.proseMilitary,
  'prose_rus_classic': Fb2Genre.proseRusClassic,
  'prose_su_classics': Fb2Genre.proseSuClassics,
  'psy_alassic': Fb2Genre.psyAlassic,
  'psy_childs': Fb2Genre.psyChilds,
  'psy_generic': Fb2Genre.psyGeneric,
  'psy_personal': Fb2Genre.psyPersonal,
  'psy_sex_and_family': Fb2Genre.psySexAndFamily,
  'psy_social': Fb2Genre.psySocial,
  'psy_theraphy': Fb2Genre.psyTheraphy,
  'real_estate': Fb2Genre.realEstate,
  'ref_dict': Fb2Genre.refDict,
  'ref_encyc': Fb2Genre.refEncyc,
  'ref_guide': Fb2Genre.refGuide,
  'ref_ref': Fb2Genre.refRef,
  'reference': Fb2Genre.reference,
  'religion': Fb2Genre.religion,
  'religion_esoterics': Fb2Genre.religionEsoterics,
  'religion_rel': Fb2Genre.religionRel,
  'religion_self': Fb2Genre.religionSelf,
  'russian_contemporary': Fb2Genre.russianContemporary,
  'russian_fantasy': Fb2Genre.russianFantasy,
  'sci_biology': Fb2Genre.sciBiology,
  'sci_chem': Fb2Genre.sciChem,
  'sci_culture': Fb2Genre.sciCulture,
  'sci_history': Fb2Genre.sciHistory,
  'sci_juris': Fb2Genre.sciJuris,
  'sci_linguistic': Fb2Genre.sciLinguistic,
  'sci_math': Fb2Genre.sciMath,
  'sci_medicine': Fb2Genre.sciMedicine,
  'sci_philosophy': Fb2Genre.sciPhilosophy,
  'sci_phys': Fb2Genre.sciPhys,
  'sci_politics': Fb2Genre.sciPolitics,
  'sci_religion': Fb2Genre.sciReligion,
  'sci_tech': Fb2Genre.sciTech,
  'science': Fb2Genre.science,
  'sf': Fb2Genre.sf,
  'sf_action': Fb2Genre.sfAction,
  'sf_cyberpunk': Fb2Genre.sfCyberpunk,
  'sf_detective': Fb2Genre.sfDetective,
  'sf_fantasy': Fb2Genre.sfFantasy,
  'sf_heroic': Fb2Genre.sfHeroic,
  'sf_history': Fb2Genre.sfHistory,
  'sf_horror': Fb2Genre.sfHorror,
  'sf_humor': Fb2Genre.sfHumor,
  'sf_social': Fb2Genre.sfSocial,
  'sf_space': Fb2Genre.sfSpace,
  'short_story': Fb2Genre.shortStory,
  'sketch': Fb2Genre.sketch,
  'small_business': Fb2Genre.smallBusiness,
  'sociology_book': Fb2Genre.sociologyBook,
  'stock': Fb2Genre.stock,
  'thriller': Fb2Genre.thriller,
  'upbringing_book': Fb2Genre.upbringingBook,
  'vampire_book': Fb2Genre.vampireBook,
  'visual_arts': Fb2Genre.visualArts,
  'unrecognised': Fb2Genre.unrecognised,
};
