name: build

on: [push]

jobs:
  build-dart-latest:

    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dart pub upgrade
    - name: Run dependency validator
      run: dart pub run dependency_validator --ignore dart_code_metrics
    - name: Run analyzer
      run:  |
        dart analyze --fatal-warnings --fatal-infos lib
        dart analyze --fatal-warnings --fatal-infos test
    - name: Run dart-code-metrics
      run: dart pub run dart_code_metrics:metrics lib
    - name: Run formatter
      run: dart format --set-exit-if-changed .
    - name: Run tests
      run: dart test
